# Python stubs generated by omniidl from sistema.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Sistema"
#
__name__ = "Sistema"
_0_Sistema = omniORB.openModule("Sistema", r"sistema.idl")
_0_Sistema__POA = omniORB.openModule("Sistema__POA", r"sistema.idl")


# interface Calculadora
_0_Sistema._d_Calculadora = (omniORB.tcInternal.tv_objref, "IDL:Sistema/Calculadora:1.0", "Calculadora")
omniORB.typeMapping["IDL:Sistema/Calculadora:1.0"] = _0_Sistema._d_Calculadora
_0_Sistema.Calculadora = omniORB.newEmptyClass()
class Calculadora :
    _NP_RepositoryId = _0_Sistema._d_Calculadora[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Sistema.Calculadora = Calculadora
_0_Sistema._tc_Calculadora = omniORB.tcInternal.createTypeCode(_0_Sistema._d_Calculadora)
omniORB.registerType(Calculadora._NP_RepositoryId, _0_Sistema._d_Calculadora, _0_Sistema._tc_Calculadora)

# Calculadora operations and attributes
Calculadora._d_quadrado = ((omniORB.tcInternal.tv_double, ), (omniORB.tcInternal.tv_double, ), None)

# Calculadora object reference
class _objref_Calculadora (CORBA.Object):
    _NP_RepositoryId = Calculadora._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def quadrado(self, *args):
        return self._obj.invoke("quadrado", _0_Sistema.Calculadora._d_quadrado, args)

omniORB.registerObjref(Calculadora._NP_RepositoryId, _objref_Calculadora)
_0_Sistema._objref_Calculadora = _objref_Calculadora
del Calculadora, _objref_Calculadora

# Calculadora skeleton
__name__ = "Sistema__POA"
class Calculadora (PortableServer.Servant):
    _NP_RepositoryId = _0_Sistema.Calculadora._NP_RepositoryId


    _omni_op_d = {"quadrado": _0_Sistema.Calculadora._d_quadrado}

Calculadora._omni_skeleton = Calculadora
_0_Sistema__POA.Calculadora = Calculadora
omniORB.registerSkeleton(Calculadora._NP_RepositoryId, Calculadora)
del Calculadora
__name__ = "Sistema"

#
# End of module "Sistema"
#
__name__ = "sistema_idl"

_exported_modules = ( "Sistema", )

# The end.
